package com.rexco.exercise;

import com.rexco.AppConstant;
import com.zaxxer.hikari.HikariDataSource;
import net.ttddyy.dsproxy.support.ProxyDataSourceBuilder;

import javax.sql.DataSource;
import java.sql.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;


public class Exercise2 {
    public static final String SELECT_QUERY = "SELECT * FROM users WHERE id IN ("+ expandQuestionMarks(List.of("?","?","?","?","?"))+")";
    public static final String INSERT_QUERY = "INSERT INTO users (first_name, last_name, registration_date) VALUES (?,?,?)";



    public static void main(String[] args)throws SQLException {
        DataSource dataSource = createDataSource();

        try(Connection connection = dataSource.getConnection()){

//            try(PreparedStatement statement = connection.prepareStatement(INSERT_QUERY, Statement.RETURN_GENERATED_KEYS)){
//                statement.setString(1, "Aaaa");
//                statement.setString(2, "Arggh");
//                statement.setObject(3, LocalDateTime.now());
//
//                statement.addBatch();
//
//                statement.setString(1, "Bbbb");
//                statement.setString(2, "Brrrrr");
//                statement.setObject(3, LocalDateTime.now());
//
//                statement.addBatch();
//
//                statement.setString(1, "Cccc");
//                statement.setString(2, "Crrrraaa");
//                statement.setObject(3, LocalDateTime.now());
//
//                statement.addBatch();
//
//                int[] rowsArray = statement.executeBatch();
//
//
//                final ResultSet generatedKeys = statement.getGeneratedKeys();
//
//                Long autogeneratedId = null;
//
//                while(generatedKeys.next()){
//                    autogeneratedId =  generatedKeys.getLong("id");
//
//                        System.out.println("Inserted [" + rowsArray.length + "] row into table" +
//                                " users, with autogenerated id [" + autogeneratedId + "]");
//
//                }
//
//            }

            try(PreparedStatement statement = connection.prepareStatement(SELECT_QUERY, Statement.RETURN_GENERATED_KEYS)){
                setParams(statement, List.of(1,2,3,4,5));

                ResultSet resultSet = statement.executeQuery();

                while(resultSet.next()){
                    int id = resultSet.getInt("id");
                    String firstName = resultSet.getString("first_name");
                    String lastName = resultSet.getString("last_name");
                    LocalDateTime registrationDate = resultSet.getObject("registration_date", LocalDateTime.class);

                    System.out.println("Found user: " + id + " | " + firstName +
                            " | " + lastName + " | " + registrationDate);
                }
            }
        }

    }

    public static String expandQuestionMarks(List<?> params) {
        return params.stream().map(i -> "?").collect(Collectors.joining(","));
    }

    public static void setParams(PreparedStatement stmt, List<Integer> params) throws
            SQLException {
        for (int i = 0; i < params.size(); i++) {
            stmt.setInt(i + 1, params.get(i));
        }
    }

    private static DataSource createDataSource(){
        HikariDataSource hikariDataSource = new HikariDataSource();
        hikariDataSource.setJdbcUrl(AppConstant.URL_CONNECTION);
        hikariDataSource.setUsername(AppConstant.DB_USERNAME);
        hikariDataSource.setPassword(AppConstant.DB_PASSWORD);

        return ProxyDataSourceBuilder.create(hikariDataSource).logQueryToSysOut().build();
    }

}
