package com.rexco;

import com.zaxxer.hikari.HikariDataSource;

import javax.sql.DataSource;

import java.sql.*;
import java.time.LocalDateTime;

import static com.rexco.AppConstant.*;

public class BankApp2 {
    public static final String INSERT_USER_QUERY = "INSERT INTO users(first_name, last_name, registration_date) " +
            "VALUES (?,?,?)";
    public static void main(String[] args) throws SQLException {
        DataSource dataSource  = createDataSource();

        try(Connection connection = dataSource.getConnection()){

            try(PreparedStatement statement =  connection.prepareStatement(INSERT_USER_QUERY, Statement.RETURN_GENERATED_KEYS)){
                statement.setString(1, "Bola");
                statement.setString(2, "Zayne");
                statement.setObject(3, LocalDateTime.now());

                statement.addBatch();

                statement.setString(1, "kedi");
                statement.setString(2, "Ellie");
                statement.setObject(3, LocalDateTime.now());

                statement.addBatch();

                 final int[] insertCount = statement.executeBatch();

                final ResultSet autogenerateId = statement.getGeneratedKeys();
                autogenerateId.next();
                int count = 0;

               while(autogenerateId.next()){
                       System.out.println("Inserted [" + count++ + "] row into table" +
                               " users, with autogenerated id [" + autogenerateId.getInt("id") + "]");

               }



            }
        }
    }

    private static DataSource createDataSource(){
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setJdbcUrl(URL_CONNECTION);
        dataSource.setUsername(DB_USERNAME);
        dataSource.setPassword(DB_PASSWORD);

        return dataSource;
    }
}
